#!/bin/bash

set -e

BOARD_DIR="$(dirname $0)"
EFI_PART=${BINARIES_DIR}/efi-part
EFI_DIR=${EFI_PART}/EFI/BOOT

# Create the EFI system partition with startup script and kernel
# executable according to the UEFI standard.
rm -rf ${EFI_DIR}
mkdir -p ${EFI_DIR}
cp ${BOARD_DIR}/startup.nsh ${EFI_PART}/
ln -sf ${BINARIES_DIR}/Image ${EFI_DIR}/bootaa64.efi

# BL1 and FIP needs to be concatenated into a single flash device.
rm -rf ${BINARIES_DIR}/flash.bin
dd if=${BINARIES_DIR}/bl1.bin of=${BINARIES_DIR}/flash.bin bs=4096 conv=notrunc
dd if=${BINARIES_DIR}/fip.bin of=${BINARIES_DIR}/flash.bin seek=64 bs=4096 conv=notrunc
