#!/bin/bash

set -e

BOARD_DIR="$(dirname $0)"
EFI_PART=${BINARIES_DIR}/efi-part
EFI_DIR=${EFI_PART}/EFI/BOOT

# Create the EFI system partition with startup script and kernel
# executable according to the UEFI standard.
mkdir -p ${EFI_DIR}
cp ${BOARD_DIR}/startup.nsh ${EFI_PART}/
ln -sf ${BINARIES_DIR}/Image ${EFI_DIR}/bootaa64.efi

# The FVP SGI-575 platform wants the NOR flash to be 64M and gzipped.
create_nor_flash() {
  dd if=/dev/zero of=${1} bs=256K count=256
  gzip ${1}
  mv ${1}.gz ${1}
}

rm -rf ${BINARIES_DIR}/nor_flash*
create_nor_flash ${BINARIES_DIR}/nor_flash1.bin
create_nor_flash ${BINARIES_DIR}/nor_flash2.bin
