################################################################################
#
# skeleton-slashpackage
#
################################################################################

SKELETON_SLASHPACKAGE_ADD_TOOLCHAIN_DEPENDENCY = NO
SKELETON_SLASHPACKAGE_ADD_SKELETON_DEPENDENCY = NO
SKELETON_SLASHPACKAGE_DEPENDENCIES = skeleton-init-common
SKELETON_SLASHPACKAGE_PROVIDES = skeleton

SKELETON_SLASHPACKAGE_VERSION = 0.0.1
SKELETON_SLASHPACKAGE_SITE = file:///home/sysadm/senzillaos/release/latest
SKELETON_SLASHPACKAGE_LICENSE = ISC
SKELETON_SLASHPACKAGE_LICENSE_FILES = LICENSE
SKELETON_SLASHPACKAGE_INSTALL_STAGING = YES

SKELETON_SLASHPACKAGE_KCONFIG_FILE = $(call qstrip,$(BR2_PACKAGE_SKELETON_SLASHPACKAGE_CONFIG))
SKELETON_SLASHPACKAGE_MAKE_ENV = $(HOST_MAKE_ENV)

SKELETON_SLASHPACKAGE_DEPENDENCIES += host-python3-kconfiglib host-fakeroot \
	host-s6-portable-utils host-s6-linux-init host-s6-rc

define SKELETON_SLASHPACKAGE_USERS
	log -1 log -1 * - - - Log writer
	syslog -1 syslog -1 * - - - Syslog reader
	klog -1 klog -1 * - - - Kernel log reader
endef

define SKELETON_SLASHPACKAGE_BUILD_CMDS
	$(HOST_MAKE_ENV) $(MAKE) -C $(@D)
endef

define SKELETON_SLASHPACKAGE_INSTALL_STAGING_CMDS
	$(SKELETON_SLASHPACKAGE_MAKE_ENV) $(MAKE) DESTDIR="$(STAGING_DIR)" -C $(@D) install
endef

define SKELETON_SLASHPACKAGE_INSTALL_TARGET_CMDS
	$(SKELETON_SLASHPACKAGE_MAKE_ENV) $(MAKE) DESTDIR="$(TARGET_DIR)" -C $(@D) install
endef

define SKELETON_SLASHPACKAGE_TARGET_FINALIZE
	$(SKELETON_SLASHPACKAGE_MAKE_ENV) $(MAKE) DESTDIR="$(TARGET_DIR)" \
		-C $(BUILD_DIR)/skabox-$(SKELETON_SLASHPACKAGE_VERSION) finalize
endef

SKELETON_SLASHPACKAGE_TARGET_FINALIZE_HOOKS += SKELETON_SLASHPACKAGE_TARGET_FINALIZE

$(eval $(kconfig-package))
